"""
Ứng dụng mã hóa/giải mã file bằng DES
==================================

Dự án mini: Xây dựng ứng dụng mã hóa/giải mã tệp bằng DES 
với khóa do người dùng chọn.

Bài tập thực hành Cybersecurity - Data Privacy
"""

import os
import sys
from des import encrypt_des, decrypt_des
import time
import hashlib


class FileCrypto:
    def __init__(self):
        self.version = "1.0"
        self.author = "Student Cybersecurity"
        self.supported_formats = ['.txt', '.md',
                                  '.py', '.js', '.html', '.css', '.json']

    def validate_key(self, key):
        """Kiểm tra tính hợp lệ của key"""
        if not key:
            return False, "Key không được để trống"
        if len(key) < 8:
            return False, "Key phải có ít nhất 8 ký tự"
        if len(key) > 64:
            return False, "Key không được quá 64 ký tự"
        return True, "Key hợp lệ"

    def get_file_info(self, filepath):
        """Lấy thông tin file"""
        if not os.path.exists(filepath):
            return None

        stat = os.stat(filepath)
        return {
            'size': stat.st_size,
            'modified': time.ctime(stat.st_mtime),
            'extension': os.path.splitext(filepath)[1],
            'name': os.path.basename(filepath)
        }

    def encrypt_file(self, input_file, output_file, key):
        """
        Mã hóa file

        Args:
            input_file (str): Đường dẫn file đầu vào
            output_file (str): Đường dẫn file đầu ra
            key (str): Key mã hóa

        Returns:
            tuple: (success, message, stats)
        """
        try:
            # Kiểm tra key
            valid, msg = self.validate_key(key)
            if not valid:
                return False, msg, None

            # Kiểm tra file đầu vào
            if not os.path.exists(input_file):
                return False, f"File không tồn tại: {input_file}", None

            file_info = self.get_file_info(input_file)

            # Đọc file
            try:
                with open(input_file, 'r', encoding='utf-8') as f:
                    content = f.read()
            except UnicodeDecodeError:
                # Thử với encoding khác
                with open(input_file, 'r', encoding='latin-1') as f:
                    content = f.read()

            if not content:
                return False, "File trống hoặc không đọc được", None

            # Mã hóa
            start_time = time.time()
            encrypted_content = encrypt_des(content, key)
            end_time = time.time()

            # Tạo metadata
            metadata = {
                'original_filename': file_info['name'],
                'original_size': len(content),
                'encryption_time': time.strftime('%Y-%m-%d %H:%M:%S'),
                # Chỉ lưu hash để verify
                'key_hash': hashlib.sha256(key.encode()).hexdigest()[:16],
                'version': self.version
            }

            # Tạo nội dung file mã hóa với metadata
            final_content = f"""# DES ENCRYPTED FILE
# Generated by FileCrypto v{self.version}
# Original: {metadata['original_filename']}
# Size: {metadata['original_size']} bytes
# Time: {metadata['encryption_time']}
# Key Hash: {metadata['key_hash']}
# ==========================================
{encrypted_content}"""

            # Ghi file đã mã hóa
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(final_content)

            # Thống kê
            stats = {
                'original_size': len(content),
                'encrypted_size': len(final_content),
                'compression_ratio': len(final_content) / len(content),
                'time_taken': end_time - start_time,
                'key_length': len(key),
                'file_info': file_info,
                'metadata': metadata
            }

            return True, "Mã hóa thành công", stats

        except Exception as e:
            return False, f"Lỗi: {str(e)}", None

    def decrypt_file(self, input_file, output_file, key):
        """
        Giải mã file

        Args:
            input_file (str): Đường dẫn file mã hóa
            output_file (str): Đường dẫn file sau giải mã
            key (str): Key giải mã

        Returns:
            tuple: (success, message, stats)
        """
        try:
            # Kiểm tra key
            valid, msg = self.validate_key(key)
            if not valid:
                return False, msg, None

            # Kiểm tra file đầu vào
            if not os.path.exists(input_file):
                return False, f"File không tồn tại: {input_file}", None

            # Đọc file mã hóa
            with open(input_file, 'r', encoding='utf-8') as f:
                full_content = f.read()

            if not full_content:
                return False, "File trống", None

            # Phân tích metadata và nội dung
            lines = full_content.split('\n')

            # Tìm dòng phân cách
            separator_index = -1
            metadata = {}

            for i, line in enumerate(lines):
                if line.strip() == '# ==========================================':
                    separator_index = i
                    break
                elif line.startswith('# Original:'):
                    metadata['original_filename'] = line.split(': ', 1)[1]
                elif line.startswith('# Size:'):
                    metadata['original_size'] = line.split(': ', 1)[1]
                elif line.startswith('# Time:'):
                    metadata['encryption_time'] = line.split(': ', 1)[1]
                elif line.startswith('# Key Hash:'):
                    metadata['key_hash'] = line.split(': ', 1)[1]

            if separator_index == -1:
                return False, "File không phải format mã hóa hợp lệ", None

            # Lấy nội dung mã hóa
            encrypted_content = '\n'.join(lines[separator_index + 1:])

            # Verify key (optional)
            key_hash = hashlib.sha256(key.encode()).hexdigest()[:16]
            if 'key_hash' in metadata and metadata['key_hash'] != key_hash:
                print(f"⚠️  Warning: Key hash không khớp. Có thể key không đúng.")

            # Giải mã
            start_time = time.time()
            decrypted_content = decrypt_des(encrypted_content, key)
            end_time = time.time()

            # Ghi file đã giải mã
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(decrypted_content)

            # Thống kê
            stats = {
                'encrypted_size': len(full_content),
                'decrypted_size': len(decrypted_content),
                'time_taken': end_time - start_time,
                'key_length': len(key),
                'metadata': metadata
            }

            return True, "Giải mã thành công", stats

        except Exception as e:
            return False, f"Lỗi: {str(e)}", None

    def print_stats(self, stats, operation):
        """In thống kê chi tiết"""
        if not stats:
            return

        print(f"\n📊 THỐNG KÊ {operation.upper()}:")
        print("="*50)

        if operation == "mã hóa":
            print(
                f"📄 File gốc: {stats.get('file_info', {}).get('name', 'N/A')}")
            print(f"📏 Kích thước gốc: {stats['original_size']:,} ký tự")
            print(f"🔒 Kích thước mã hóa: {stats['encrypted_size']:,} ký tự")
            print(f"📈 Tỷ lệ nén: {stats['compression_ratio']:.2f}")

            if 'metadata' in stats:
                print(
                    f"🕒 Thời gian mã hóa: {stats['metadata']['encryption_time']}")
                print(f"🔑 Key hash: {stats['metadata']['key_hash']}")

        else:
            print(
                f"🔒 Kích thước file mã hóa: {stats['encrypted_size']:,} ký tự")
            print(
                f"📄 Kích thước sau giải mã: {stats['decrypted_size']:,} ký tự")

            if 'metadata' in stats:
                print(
                    f"📁 File gốc: {stats['metadata'].get('original_filename', 'N/A')}")
                print(
                    f"🕒 Thời gian mã hóa: {stats['metadata'].get('encryption_time', 'N/A')}")

        print(f"🔑 Độ dài key: {stats['key_length']} ký tự")
        print(f"⏱️  Thời gian xử lý: {stats['time_taken']:.4f} giây")


def create_sample_files():
    """Tạo các file mẫu để test"""

    # File mẫu 1: Văn bản tiếng Việt
    sample1 = """Bài tập thực hành DES - Cybersecurity và Data Privacy

Đây là file mẫu để test ứng dụng mã hóa DES.

Nội dung bao gồm:
✅ Văn bản tiếng Việt có dấu
✅ Số: 123456789
✅ Ký tự đặc biệt: !@#$%^&*()
✅ English text: Hello World!

DES (Data Encryption Standard) là thuật toán mã hóa khối 64-bit
với key 56-bit hiệu dụng, sử dụng mạng Feistel 16 rounds.

Thuật toán này đã được sử dụng rộng rãi từ 1977-2001 nhưng
hiện tại không còn an toàn do key size nhỏ.

Tuy nhiên, DES vẫn có giá trị giáo dục cao để hiểu nguyên lý
mã hóa khối và cấu trúc Feistel.

Một số tính chất quan trọng của DES:
- Block size: 64-bit
- Key size: 56-bit (64-bit với parity)
- Rounds: 16 Feistel rounds
- S-boxes: 8 boxes, mỗi box 6→4 bit
- Permutations: Initial và Final

[Kết thúc file mẫu 1]"""

    # File mẫu 2: Code Python
    sample2 = """# Sample Python code for DES demo
# ================================

def simple_des_demo():
    \"\"\"Demo function for DES\"\"\"
    
    # Sample data
    plaintext = "HELLO WORLD"
    key = "MYKEY123"
    
    print(f"Plaintext: {plaintext}")
    print(f"Key: {key}")
    
    # Encrypt
    encrypted = encrypt_des(plaintext, key)
    print(f"Encrypted: {encrypted}")
    
    # Decrypt
    decrypted = decrypt_des(encrypted, key)
    print(f"Decrypted: {decrypted}")
    
    # Verify
    assert plaintext == decrypted, "Encryption/Decryption failed!"
    print("✅ Success!")

if __name__ == "__main__":
    simple_des_demo()
"""

    # File mẫu 3: JSON config
    sample3 = """{
    "application": "DES File Crypto",
    "version": "1.0",
    "author": "Student Cybersecurity",
    "settings": {
        "default_key_length": 8,
        "max_file_size": "10MB",
        "supported_formats": [".txt", ".md", ".py", ".js", ".html", ".css", ".json"],
        "encryption": {
            "algorithm": "DES",
            "block_size": 64,
            "key_size": 56,
            "rounds": 16
        },
        "security": {
            "use_salt": false,
            "key_derivation": "none",
            "note": "Educational purposes only - DO NOT USE IN PRODUCTION"
        }
    },
    "demo_data": {
        "sample_plaintexts": [
            "HELLO WORLD",
            "SECRET MESSAGE",
            "CONFIDENTIAL DATA"
        ],
        "sample_keys": [
            "MYKEY123",
            "TESTKEY1",
            "PASSWORD"
        ]
    }
}"""

    files = [
        ('sample_text.txt', sample1),
        ('sample_code.py', sample2),
        ('sample_config.json', sample3)
    ]

    created_files = []
    for filename, content in files:
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)
        created_files.append(filename)
        print(f"✅ Đã tạo: {filename} ({len(content)} ký tự)")

    return created_files


def run_complete_demo():
    """Chạy demo hoàn chỉnh với nhiều file"""
    print("\n🎬 DEMO HOÀN CHỈNH - MÃ HÓA NHIỀU FILE")
    print("="*60)

    # Tạo file mẫu
    print("📁 Tạo file mẫu...")
    sample_files = create_sample_files()

    crypto = FileCrypto()
    key = "MYKEY123"

    print(f"\n🔑 Sử dụng key: '{key}'")

    for sample_file in sample_files:
        print(f"\n🔒 Xử lý file: {sample_file}")
        print("-" * 40)

        # Tên file mã hóa và giải mã
        encrypted_file = f"{sample_file}.encrypted"
        decrypted_file = f"{sample_file}.decrypted"

        # Mã hóa
        print(f"🔐 Mã hóa {sample_file}...")
        success, message, stats = crypto.encrypt_file(
            sample_file, encrypted_file, key)

        if success:
            print(f"✅ {message}")
            crypto.print_stats(stats, "mã hóa")
        else:
            print(f"❌ {message}")
            continue

        # Giải mã
        print(f"\n🔓 Giải mã {encrypted_file}...")
        success, message, stats = crypto.decrypt_file(
            encrypted_file, decrypted_file, key)

        if success:
            print(f"✅ {message}")
            crypto.print_stats(stats, "giải mã")

            # So sánh file gốc và file đã giải mã
            with open(sample_file, 'r', encoding='utf-8') as f1, \
                    open(decrypted_file, 'r', encoding='utf-8') as f2:
                original = f1.read()
                decrypted = f2.read()

            integrity_check = original == decrypted
            print(f"\n🔍 KIỂM TRA TÍNH TOÀN VẸN:")
            print(f"{'✅' if integrity_check else '❌'} File gốc và file giải mã: {'GIỐNG NHAU' if integrity_check else 'KHÁC NHAU'}")

        else:
            print(f"❌ {message}")


def main():
    """Chương trình chính"""
    crypto = FileCrypto()

    print("="*70)
    print("🔐 ỨNG DỤNG MÃ HÓA/GIẢI MÃ FILE BẰNG DES")
    print(f"📌 Version: {crypto.version} | Author: {crypto.author}")
    print("⚠️  CHỈ DÀNH CHO MỤC ĐÍCH GIÁO DỤC - KHÔNG SỬ DỤNG TRONG SẢN XUẤT")
    print("="*70)

    while True:
        print("\n📋 MENU:")
        print("1. Tạo file mẫu")
        print("2. Mã hóa file")
        print("3. Giải mã file")
        print("4. Demo hoàn chỉnh")
        print("5. Xem thông tin file")
        print("6. Thoát")

        choice = input("\n🔤 Chọn chức năng (1-6): ").strip()

        if choice == '1':
            print("\n📁 TẠO FILE MẪU")
            print("="*30)
            sample_files = create_sample_files()
            print(f"\n✅ Đã tạo {len(sample_files)} file mẫu")
            print("💡 Bạn có thể sử dụng các file này để test mã hóa")

        elif choice == '2':
            print("\n🔐 MÃ HÓA FILE")
            print("="*30)
            input_file = input("📁 Nhập đường dẫn file cần mã hóa: ").strip()
            output_file = input(
                "💾 Nhập đường dẫn file output (.encrypted): ").strip()

            if not output_file.endswith('.encrypted'):
                output_file += '.encrypted'

            key = input("🔑 Nhập key mã hóa (8+ ký tự): ").strip()

            print("\n🔄 Đang mã hóa...")
            success, message, stats = crypto.encrypt_file(
                input_file, output_file, key)

            if success:
                print(f"✅ {message}")
                crypto.print_stats(stats, "mã hóa")
                print(f"💾 File mã hóa đã lưu tại: {output_file}")
            else:
                print(f"❌ {message}")

        elif choice == '3':
            print("\n🔓 GIẢI MÃ FILE")
            print("="*30)
            input_file = input(
                "🔒 Nhập đường dẫn file cần giải mã (.encrypted): ").strip()
            output_file = input("📄 Nhập đường dẫn file output: ").strip()
            key = input("🔑 Nhập key giải mã: ").strip()

            print("\n🔄 Đang giải mã...")
            success, message, stats = crypto.decrypt_file(
                input_file, output_file, key)

            if success:
                print(f"✅ {message}")
                crypto.print_stats(stats, "giải mã")
                print(f"📄 File giải mã đã lưu tại: {output_file}")
            else:
                print(f"❌ {message}")

        elif choice == '4':
            run_complete_demo()

        elif choice == '5':
            print("\n📊 THÔNG TIN FILE")
            print("="*30)
            filepath = input("📁 Nhập đường dẫn file: ").strip()

            file_info = crypto.get_file_info(filepath)
            if file_info:
                print(f"📄 Tên file: {file_info['name']}")
                print(f"📏 Kích thước: {file_info['size']:,} bytes")
                print(f"📅 Sửa đổi lần cuối: {file_info['modified']}")
                print(f"🏷️  Extension: {file_info['extension']}")

                if file_info['extension'] in crypto.supported_formats:
                    print("✅ Format được hỗ trợ")
                else:
                    print("⚠️  Format không chính thức được hỗ trợ")
            else:
                print("❌ File không tồn tại")

        elif choice == '6':
            print("\n👋 Cảm ơn bạn đã sử dụng FileCrypto!")
            print("📚 Hy vọng bạn đã học được nhiều điều về DES!")
            break

        else:
            print("❌ Lựa chọn không hợp lệ!")


if __name__ == "__main__":
    main()
